#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	Julak Bantur
# //	Dscription: Xray MultiPort
# //	email: putrameratus2@gmail.com
# //  telegram: https://t.me/Cibut2d
# //====================================================
# // font color configuration | JULAK BANTUR AUTOSCRIPT
### COLOR IJO ###
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
VC="\e[0m"
Green="\e[92;1m"
BICyan='\033[1;96m'
BIYellow='\033[1;93m'
WH='\033[1;37m'
y='\033[1;33m' #yellow
l='\033[0;37m'
BGX="\033[42m"
CYAN="\033[96m"
z="\033[96m"
zx="\033[97;1m" # // putih
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[1;32m'
grenbo="\e[92;1m"
purple="\033[1;95m"
YELL='\033[0;33m'
cyan="\033[1;36m"
c="\033[5;33m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
##Bawa santai haja sanak ae
echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "${CYAN} Autoscript Ini Sudah Melalui beberapa kali update ${NC}" 
echo -e "${purple} Tidak bisa di pungkiri kalau bahan2 script hasil comot sana sini tapi tentunya sudah atas ijin developer lain ${{RED}"
echo -e "${grenbo} Terimakasih Sudah Menggunakan script ini${NC}"
echo -e "${grenbo} BY JULAK BANTUR${NC}"
echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
menu

###@Jangan_Lupa_Ngopi###
###@Biar_Plongggggg###
